### PR TITLE
Fix operation ordering issue during inlining of operations into dispatch region

### LINKED ISSUE #5151: unidirectional_lstm.mlir doesn't work with -iree-flow-dispatch-linalg-on-tensors
**Describe the bug**
This test failed in DispatchLinalgOnTensorsPass. The error log can be found at https://gist.github.com/hanhanW/89a177694616a43a35da7abd11152d51

Short log:

```
error: operand #0 does not dominate this use
```

This failed in dispatch function creation stage, so it does not work on both CPU and GPU.

**To Reproduce**

Run: `iree-run-mlir iree/test/e2e/models/unidirectional_lstm.mlir -iree-hal-target-backends=vulkan-spirv -function-input="1x5xf32=[0,1,0,3,4]" -iree-flow-dispatch-linalg-on-tensors -iree-codegen-spirv-experimental-linalg-on-tensors -function-input="1x5x2x2xf32=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]"`

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
In general the operations cloned into a dispatch region could form a
DAG. These operations have to be cloned while keeping the order
amongst them consistent to not violate use-def chains. This changes
adds a method to clone the operations in the right order. Also cleans
up the dispatch region creation code.

Fixes #5151.

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
@benvanik This change could potentially be done in the canonicalizer, but I got a bit lost in the interfaces and wasnt sure if it is actually worth having so much stress on the canonicalizers so as to pull in operands with operands into the dispatch region as well. So I aborted that plan, and just fixed the ordering issue while pulling the ops into the dispatch region during creation itself.

File: iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp [hunk 1]
```diff
@@ -320,14 +322,106 @@ static Value buildFlowWorkgroupInfoOp(OpBuilder &b, unsigned dim) {
...
+
+  llvm::SmallMapVector<Operation *, SmallVector<Operation *>, 16>
+      insertAfterMap;
+  llvm::SetVector<Operation *> allOps(ops.begin(), ops.end());
+  llvm::SetVector<Operation *> leafOps = allOps;
+  // For each operation compute the list of operations in `ops` that use its
+  // results. Also compute the operations that form the leafs of the DAG of
+  // operations in `ops`.
+  for (auto op : ops) {
+    // insertAfterList.emplace_back(ElementTy{op, {}});
```
Comment (benvanik) [inline iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp:345]: unused code

File: iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp [hunk 2]
```diff
@@ -320,14 +322,106 @@ static Value buildFlowWorkgroupInfoOp(OpBuilder &b, unsigned dim) {
...
+          nextReadyOps.push_back(insertAfterOp);
+          orderedOps.push_back(insertAfterOp);
+          processed.insert(insertAfterOp);
+        }
+      }
+    }
+    std::swap(nextReadyOps, readyOps);
+  }
+
+  LLVM_DEBUG({
```
Comment (benvanik) [inline iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp:404]: this is a lot of debug spew (here and above) - is this enabled with -debug by default?

File: iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir [hunk 3]
```diff
@@ -13,7 +13,7 @@ func @tensor(%arg0 : tensor<?x?xf32>, %arg1 : tensor<?x?xf32>,
 // CHECK-SAME:   %[[ARG1:[a-zA-Z0-9_]+]]: tensor<?x?xf32>
 // CHECK-SAME:   %[[ARG2:[a-zA-Z0-9_]+]]: tensor<?x?xf32>
 //      CHECK:   flow.dispatch.workgroups
-// CHECK-SAME:     (%[[ARG0]], %[[ARG1]], %[[ARG2]])
+// CHECK-SAME:     (%[[ARG2]], %[[ARG1]], %[[ARG0]])
```
Comment (benvanik) [inline iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir:16]: It's weird these are reversed - is there a reason for that? It looks like the usage is `%arg0, %arg1` in the matmul too, so that they are transposed here is odd. I know it's still correct, but when reading through IR these kind of things add a mental tax :)

File: iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir [hunk 4]
```diff
@@ -75,11 +75,11 @@ func @generic_op(%A: tensor<?x?xf32>, %B: tensor<?xf32>) -> tensor<?x?xf32> {
 //  CHECK-DAG:   %[[D0:.+]] = memref.dim %[[ARG0]], %[[C0]]
 //  CHECK-DAG:   %[[D1:.+]] = memref.dim %[[ARG0]], %[[C1]]
 //      CHECK:   flow.dispatch.workgroups
-// CHECK-SAME:     [%[[D1]], %[[D0]], %[[C1]]](%[[ARG0]], %[[ARG1]], %[[D0]], %[[D1]])
-// CHECK-NEXT:     %[[ARG2:[a-zA-Z0-9_]+]]: !flow.dispatch.tensor<readonly:?x?xf32>
-// CHECK-SAME:     %[[ARG3:[a-zA-Z0-9_]+]]: !flow.dispatch.tensor<readonly:?xf32>
-// CHECK-SAME:     %[[ARG4:[a-zA-Z0-9_]+]]: index
-// CHECK-SAME:     %[[ARG5:[a-zA-Z0-9_]+]]: index
+// CHECK-SAME:     [%[[D1]], %[[D0]], %[[C1]]](%[[D1]], %[[D0]], %[[ARG1]], %[[ARG0]])
```
Comment (benvanik) [inline iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir:78]: here too - the inversion is really unfortunate

**Review by benvanik — CHANGES_REQUESTED** [review]
Overall looks fine - can always extract it out later on if we want. Am concerned about the consistent inversion of argument ordering, though - if it's a reasonable thing to fix that'd be really nice!

File: iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp (hunk 2 above)
Comment (MaheshRavishankar) [reply iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp:404]: I guess so. Is there a way to hide it even further. I can remove it if it is too much.

File: iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir (hunk 3 above)
Comment (MaheshRavishankar) [reply iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir:16]: The original order was because I took the values and explicitly did a reverse of that. I am not sure I remember the rationale for that, but it was mostly to keep it consistent with what `valuesDefinedFromAbove` gives. But that was a hack. There is really no way of enforcing the order. Even `valuesDefinedFromAbove` does not actually specify that there is any ordering there. It was all mostly happy coincidence :) .  I can go back to adding the `reverse` but the reasoning there is shaky.

Comment (benvanik) [reply iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors_dynamic.mlir:16]: If it's consistently inverting the order I think reversing is fine - it's not a correctness thing, but does make it much easier to read and track the values across the various lowering stages (especially after outlining, where one can't see the usage of the values on the inside anymore). Even if only ordered right 75% of the time that's still nicer than being ordered wrong 100% of the time :)

The improvements here are great so it wouldn't be worth doing too much to fix, but if it's adding a reverse that seems worth it :)

File: iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp (hunk 2 above)
Comment (MaheshRavishankar) [reply iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp]: Looks like DEBUG_WITH_TYPE is the thing to use.

Comment (MaheshRavishankar) [reply iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp]: Using DEBUG_WITH_TYPE. That makes the debug spew guarded by DEBUG_TYPE.

File: iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp [hunk 5]
```diff
@@ -320,14 +322,106 @@ static Value buildFlowWorkgroupInfoOp(OpBuilder &b, unsigned dim) {
...
+              return !operandDefiningOp || processed.count(operandDefiningOp);
+            })) {
+          nextReadyOps.push_back(insertAfterOp);
+          orderedOps.push_back(insertAfterOp);
+          processed.insert(insertAfterOp);
+        }
+      }
+    }
+    std::swap(nextReadyOps, readyOps);
+  }
```
Comment (hanhanW) [inline iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp:402]: I do not think it worths to do batch-based BFS in this case. You can take one op from `readyOps`, look into the insertAfterMap, and insert ops to `readyOps`, and do the next round. In this case, I would rename `readyOps` as `queue`. (but keep using SmallVector type because std::queue is slow.)


(I think you are finding a topological order of a DAG, right?)

File: iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp [hunk 6]
```diff
@@ -320,14 +322,106 @@ static Value buildFlowWorkgroupInfoOp(OpBuilder &b, unsigned dim) {
...
+  });
+  assert(orderedOps.size() == ops.size());
+  return std::move(orderedOps);
+}
+
 /// Computes the values that will be eventually be used within the dispatch
 /// workgroup op but defined outside the op after all clonable operations are
 /// cloned into the region. Returns (by reference) the clonable operations too,
 /// in order in which they can be cloned within the region to satisfy use-def
 /// relationships between them.
```
Comment (hanhanW) [inline iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp:420]: I don't think the function returns anything... should we update the comment? It seems that we store the results into `valuesDefinedAbove` (by reverse it + prepend clonedOps).

**Review by hanhanW — CHANGES_REQUESTED** [review]
> Overall looks fine - can always extract it out later on if we want. Am concerned about the consistent inversion of argument ordering, though - if it's a reasonable thing to fix that'd be really nice!

I think this is because of the readability of the IR. I saw a comment in the code:

```
  // Reverse the values. This is not for correctness, but more for readability
  // of the IR.
```

**Review by benvanik — APPROVED** [review]

File: iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp (hunk 6 above)
Comment (MaheshRavishankar) [reply iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp:416]: The comment says "returns by reference".

File: iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp (hunk 5 above)
Comment (hanhanW) [reply iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp:398]: My point is that  topological sorting is a classic problem, and the pseudo code in wiki is also processing one by one, not a batch. Another point is that this will be simpler and cleaner to me. We don't even need a `nextReadyOps` variable. When I first time looked into it, I was parsing the meaning of "batch". Then I realized that this was a normal topological sorting problem.

I clean it a bit, and found that the line reduces from 29 to 18, although most of deleted code is debug message. I'd prefer making it simple, but the current version is also okay to me.

```cpp
  SmallVector<Operation *, 16> queue = llvm::to_vector<16>(leafOps);
  while (!queue.empty()) {
    // Check all uses of `readyOp` within `ops`. If all of the operations that
    // define the operands of the user have been added to `orderedOps`, then
    // the user is ready to be scheduled.
    auto op = queue.pop_back_val();
    for (auto insertAfterOp : insertAfterMap[op]) {
      if (processed.count(insertAfterOp)) continue;
      if (llvm::all_of(insertAfterOp->getOperands(), [&](Value operand) {
            Operation *operandDefiningOp = operand.getDefiningOp();
            return !operandDefiningOp || processed.count(operandDefiningOp);
          })) {
        queue.push_back(insertAfterOp);
        orderedOps.push_back(insertAfterOp);
        processed.insert(insertAfterOp);
      }
    }
  }
```

File: iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp [hunk 7]
```diff
@@ -320,14 +322,102 @@ static Value buildFlowWorkgroupInfoOp(OpBuilder &b, unsigned dim) {
...
+  DEBUG_WITH_TYPE(DEBUG_TYPE, {
+    llvm::dbgs() << "Ops to be inlined (sorted) : \n";
+    for (auto op : orderedOps) {
+      llvm::dbgs() << "\t";
+      op->print(llvm::dbgs());
+      llvm::dbgs() << "\n";
+    }
+  });
+  assert(orderedOps.size() == ops.size());
+  return std::move(orderedOps);
```
Comment (hanhanW) [inline iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp:409]: I think we don't need `std::move` in this case. I learned that this is not needed, and it will prevent the compiler to use return-value-optimization.

https://stackoverflow.com/questions/44065808/returning-stdvector-with-stdmove
https://stackoverflow.com/questions/12953127/what-are-copy-elision-and-return-value-optimization

Some snippets:

> Whenever a local variable in a return statement is eligible for copy elision, it binds to an rvalue re­fe­rence, and thus `return t`; is identical to `return std::move(t);`.

> using an explicit std::move as this will prevent the compiler to use RVO.

File: iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp [hunk 8]
```diff
@@ -320,14 +322,102 @@ static Value buildFlowWorkgroupInfoOp(OpBuilder &b, unsigned dim) {
...
+
+  DEBUG_WITH_TYPE(DEBUG_TYPE, {
+    llvm::dbgs() << "Ops to be inlined (sorted) : \n";
+    for (auto op : orderedOps) {
+      llvm::dbgs() << "\t";
+      op->print(llvm::dbgs());
+      llvm::dbgs() << "\n";
+    }
+  });
+  assert(orderedOps.size() == ops.size());
```
Comment (hanhanW) [inline iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp:408]: Maybe add an error message for the assertion?

File: iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp [hunk 9]
```diff
@@ -443,6 +523,18 @@ static void tryToTieOperandsAndResults(
   }
 }
 
+void replaceAllUsesWithinDispatchOp(IREE::Flow::DispatchWorkgroupsOp dispatchOp,
```
Comment (hanhanW) [inline iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp:526]: I think this is outside anonymous namespace since other methods are explicitly static. Please also add `static` to this method.

**Review by hanhanW — APPROVED** [review]
Thanks, just few nits!

File: iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp (hunk 7 above)
Comment (MaheshRavishankar) [reply iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp]: Issue was i was trying to return a `SmallVector<Operation *, 16>` to a `SmallVector<Operation *>`. Warning on compiler threw me off. Removed this now.
