### PR TITLE
Fix tracking of result buffer to use if the buffer eventually maps to low dispatch output.

### LINKED ISSUE #5838: Correctness issue in variadic inputs of reduce op
There is a correctness issue in variadic inputs of mhlo.reduce op. The first output is obviously selecting the maximum value of inputs. However, it will output `0`.

```mlir
func @reduce() -> (tensor<2xi32>, tensor<2xi32>) attributes { iree.module.export } {
  %cst0 = mhlo.constant dense<-2147483648> : tensor<i32>
  %cst1 = mhlo.constant dense<0> : tensor<i32>
  %arg0 = iree.unfoldable_constant dense<[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18]]> : tensor<9x2xi32>
  %arg1 = iree.unfoldable_constant dense<[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11], [12, 13], [14, 15], [16, 17]]> : tensor<9x2xi32>
  %res0, %res1 = "mhlo.reduce"(%arg0, %arg1, %cst0, %cst1) ( {
  ^bb0(%arg2: tensor<i32>, %arg3: tensor<i32>, %arg4: tensor<i32>, %arg5: tensor<i32>):  // no predecessors
    %0 = "mhlo.compare"(%arg2, %arg4) {comparison_direction = "GE"} : (tensor<i32>, tensor<i32>) -> tensor<i1>
    %1 = "mhlo.select"(%0, %arg2, %arg4) : (tensor<i1>, tensor<i32>, tensor<i32>) -> tensor<i32>
    %2 = "mhlo.compare"(%arg2, %arg4) {comparison_direction = "EQ"} : (tensor<i32>, tensor<i32>) -> tensor<i1>
    %3 = mhlo.minimum %arg3, %arg5 : tensor<i32>
    %4 = "mhlo.select"(%0, %arg3, %arg5) : (tensor<i1>, tensor<i32>, tensor<i32>) -> tensor<i32>
    %5 = "mhlo.select"(%2, %3, %4) : (tensor<i1>, tensor<i32>, tensor<i32>) -> tensor<i32>
    "mhlo.return"(%1, %5) : (tensor<i32>, tensor<i32>) -> ()
  }) {dimensions = dense<0> : tensor<1xi64>} : (tensor<9x2xi32>, tensor<9x2xi32>, tensor<i32>, tensor<i32>) -> (tensor<2xi32>, tensor<2xi32>)
  return %res0, %res1 : tensor<2xi32>, tensor<2xi32>
}
```

Output:

```
EXEC @reduce
result[0]: hal.buffer_view
2xi32=0 0
result[1]: hal.buffer_view
2xi32=0 0
```

If delete the second pair (`%arg1`, `%cst1`), it will generate non-zero values.

```mlir
func @reduce() -> (tensor<2xi32>, tensor<2xi32>) attributes { iree.module.export } {
  %cst0 = mhlo.constant dense<-2147483648> : tensor<i32>
  %cst1 = mhlo.constant dense<0> : tensor<i32>
  %arg0 = iree.unfoldable_constant dense<[[18, 17], [16, 15], [14, 13], [12, 11], [10, 9], [8, 7], [6, 5], [4, 3], [2, 1]]> : tensor<9x2xi32>
  %arg1 = iree.unfoldable_constant dense<[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11], [12, 13], [14, 15], [16, 17]]> : tensor<9x2xi32>
  %res0 = "mhlo.reduce"(%arg0, %cst0) ( {
  ^bb0(%arg2: tensor<i32>, %arg4: tensor<i32>):  // no predecessors
    %0 = "mhlo.compare"(%arg2, %arg4) {comparison_direction = "GE"} : (tensor<i32>, tensor<i32>) -> tensor<i1>
    %1 = "mhlo.select"(%0, %arg2, %arg4) : (tensor<i1>, tensor<i32>, tensor<i32>) -> tensor<i32>
    "mhlo.return"(%1) : (tensor<i32>) -> ()
  }) {dimensions = dense<0> : tensor<1xi64>} : (tensor<9x2xi32>, tensor<i32>) -> (tensor<2xi32>)
  return %res0, %res0 : tensor<2xi32>, tensor<2xi32>
}
```

Output:

```
EXEC @reduce
result[0]: hal.buffer_view
2xi32=17 18
result[1]: hal.buffer_view
2xi32=17 18
```

The IR looks good after lowering to Linalg ops. The first operand of `linalg.yield` is generated in the same way:

```mlir
    %7 = cmpi sge, %arg0, %arg2 : i32
    %8 = select %7, %arg0, %arg2 : i32
...
    linalg.yield %8 ...
```

Two input version:

```mlir
func @reduce() -> (tensor<2xi32>, tensor<2xi32>) attributes {iree.module.export, iree.reflection = {f = "I1!R15!B5!t6d2B5!t6d2", fv = "1"}} {
  %cst = constant dense<-2147483648> : tensor<i32>
  %cst_0 = constant dense<0> : tensor<i32>
  %cst_1 = constant dense<[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18]]> : tensor<9x2xi32>
  %cst_2 = constant dense<[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11], [12, 13], [14, 15], [16, 17]]> : tensor<9x2xi32>
  %0 = iree.do_not_optimize(%cst_1) : tensor<9x2xi32>
  %1 = iree.do_not_optimize(%cst_2) : tensor<9x2xi32>
  %c-2147483648_i32 = constant -2147483648 : i32
  %2 = linalg.init_tensor [2] : tensor<2xi32>
  %3 = linalg.fill(%2, %c-2147483648_i32) : tensor<2xi32>, i32 -> tensor<2xi32>
  %c0_i32 = constant 0 : i32
  %4 = linalg.init_tensor [2] : tensor<2xi32>
  %5 = linalg.fill(%4, %c0_i32) : tensor<2xi32>, i32 -> tensor<2xi32>
  %6:2 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d1, d0)>, affine_map<(d0, d1) -> (d1, d0)>, affine_map<(d0, d1) -> (d0)>, affine_map<(d0, d1) -> (d0)>], iterator_types = ["parallel", "reduction"]} ins(%0, %1 : tensor<9x2xi32>, tensor<9x2xi32>) outs(%3, %5 : tensor<2xi32>, tensor<2xi32>) {
  ^bb0(%arg0: i32, %arg1: i32, %arg2: i32, %arg3: i32):  // no predecessors
    %7 = cmpi sge, %arg0, %arg2 : i32
    %8 = select %7, %arg0, %arg2 : i32
    %9 = cmpi eq, %arg0, %arg2 : i32
    %10 = cmpi slt, %arg1, %arg3 : i32
    %11 = select %10, %arg1, %arg3 : i32
    %12 = select %7, %arg1, %arg3 : i32
    %13 = select %9, %11, %12 : i32
    linalg.yield %8, %13 : i32, i32
  } -> (tensor<2xi32>, tensor<2xi32>)
  return %6#0, %6#1 : tensor<2xi32>, tensor<2xi32>
}
```

One input version:

```mlir
func @reduce() -> (tensor<2xi32>, tensor<2xi32>) attributes {iree.module.export, iree.reflection = {f = "I1!R15!B5!t6d2B5!t6d2", fv = "1"}} {
  %cst = constant dense<-2147483648> : tensor<i32>
  %cst_0 = constant dense<[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18]]> : tensor<9x2xi32>
  %cst_1 = constant dense<[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11], [12, 13], [14, 15], [16, 17]]> : tensor<9x2xi32>
  %0 = iree.do_not_optimize(%cst_0) : tensor<9x2xi32>
  %1 = iree.do_not_optimize(%cst_1) : tensor<9x2xi32>
  %c-2147483648_i32 = constant -2147483648 : i32
  %2 = linalg.init_tensor [2] : tensor<2xi32>
  %3 = linalg.fill(%2, %c-2147483648_i32) : tensor<2xi32>, i32 -> tensor<2xi32>
  %4 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d1, d0)>, affine_map<(d0, d1) -> (d0)>], iterator_types = ["parallel", "reduction"]} ins(%0 : tensor<9x2xi32>) outs(%3 : tensor<2xi32>) {
  ^bb0(%arg0: i32, %arg1: i32):  // no predecessors
    %5 = cmpi sge, %arg0, %arg1 : i32
    %6 = select %5, %arg0, %arg1 : i32
    linalg.yield %6 : i32
  } -> tensor<2xi32>
  return %4, %4 : tensor<2xi32>, tensor<2xi32>
}
```

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
For the case of multiple operands, the tracking to reuse the buffer
for the dispatch region output for the operations needs to be updated
to track across linalg ops that have multiple results.

Fixes  #5838

### CODE REVIEW

File: iree/compiler/Conversion/Common/LinalgBufferizePass.cpp [hunk 1]
```diff
@@ -688,10 +689,27 @@ static Value getInplaceResultBuffer(OpBuilder &b, OpResult resultValue,
...
     if (isa<IREE::Flow::DispatchTensorStoreOp>(user)) break;
-    // If user has more than one results, abort.
-    if (user->getNumResults() != 1) return nullptr;
+    // If user has more than one results, with a `LinalgOp` we can still follow
+    // the chain. For now use the `tiedOperands` cause that might result in
+    // better reuse tracking.
+    if (auto linalgOp = dyn_cast<linalg::LinalgOp>(user)) {
+      OpOperand &use = *defVal.use_begin();
+      auto tiedOperands = getTiedOperandsForLinalgOps(linalgOp);
+      Value useResult = nullptr;
```
Comment (hanhanW) [inline iree/compiler/Conversion/Common/LinalgBufferizePass.cpp:698]: [optional] we don't need to assign `nullptr`. It is `nullptr` without any assignment.

**Review by hanhanW — APPROVED** [review]

File: iree/compiler/Conversion/Common/LinalgBufferizePass.cpp (hunk 1 above)
Comment (MaheshRavishankar) [reply iree/compiler/Conversion/Common/LinalgBufferizePass.cpp:698]: Yeah, but it just makes it easier to read.
