### PR TITLE
Making iree_vm_list_resize work and switching ref cconv behavior

### LINKED ISSUE #4852: Benchmark allocates buffers in each iteration without releasing after #4767
**Describe the bug**
See a sample: https://buildkite.com/iree/iree-android-benchmark/builds/1877

The error log:

```
F ../iree/tools/iree-benchmark-module-main.cc:77] Check failed: ::iree::IsOk(_status77) ../iree/hal/vulkan/status_util.c:53: RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; vmaCreateBuffer; while invoking native function hal.allocator.allocate; while calling import
```

I can reproduce this on local side. One workaround is to reduce the number of `--benchmark_repetitions`. It is working with `--benchmark_repetitions=5` but not `--benchmark_repetitions=10`.

**To Reproduce**

- Download artifacts from https://buildkite.com/iree/iree-android-benchmark/builds/1877
- Upload files to an Android phone
- Run the model, e.g., `adb shell LD_LIBRARY_PATH=/data/local/tmp taskset 80 /data/local/tmp/benchmark_tmpdir/iree-benchmark-module --flagfile=/data/local/tmp/benchmark_tmpdir/flagfile --module_file=/data/local/tmp/benchmark_tmpdir/mobile-bert-vulkan-spirv.vmfb --driver=vulkan --benchmark_repetitions=10`

### PR DESCRIPTION
**Pull request by benvanik**
The new C HAL module was the first user of this function - now there
are tests. The new shims also assumed that arguments were not retained
(as doing so requires cleanup) but the dispatch code was double-retaining
them. I'm surprised things worked as well as they did like that o_o

Fixes #4852.

Before:
image

After:
image

### CODE REVIEW

File: iree/vm/list_test.cc [hunk 1]
```diff
@@ -229,11 +229,152 @@ TEST_F(VMListTest, Reserve) {
...
+
+  // Overwrite with [0, 5).
+  for (iree_host_size_t i = 0; i < 5; ++i) {
+    iree_vm_ref_t ref_a = MakeRef<A>((float)i);
+    IREE_ASSERT_OK(iree_vm_list_set_ref_move(list, i, &ref_a));
+  }
+
+  // Truncate to [0, 1) and then extend again.
+  IREE_ASSERT_OK(iree_vm_list_resize(list, 2));
+  IREE_ASSERT_OK(iree_vm_list_resize(list, 5));
```
Comment (hanhanW) [inline iree/vm/list_test.cc:307]: I feel it would be good if we can have variables instead of magic constants `2` and `5`.

**Review by hanhanW — APPROVED** [review]

File: iree/vm/list_test.cc (hunk 1 above)
Comment (benvanik) [reply iree/vm/list_test.cc:307]: If you have concrete suggestions I'm ok with that, but I'm not going to define kTwo and kFive :) This kind of code - which is testing exact sizes and indexing behavior - is much more readable like this than any alternative I've seen.

Comment (benvanik) [reply iree/vm/list_test.cc:307]: Clarified what is happening on these two lines with a diagram.

File: iree/base/CMakeLists.txt [hunk 2]
```diff
@@ -266,8 +266,7 @@ if(${IREE_ENABLE_RUNTIME_TRACING})
     DEPS
       ::core_headers
     DEFINES
-      # TODO(#2114): Change the mode to 2.
-      "IREE_TRACING_MODE=1"
+      "IREE_TRACING_MODE=2"
```
Comment (antiagainst) [inline iree/base/CMakeLists.txt:269]: Yay!

File: iree/vm/list_test.cc [hunk 3]
```diff
@@ -229,11 +229,161 @@ TEST_F(VMListTest, Reserve) {
...
+  }
 
-// TODO(benvanik): test resize variant.
+  // Overwrite with [0, 5).
+  for (iree_host_size_t i = 0; i < 5; ++i) {
+    iree_vm_value_t value = iree_vm_value_make_i32((int32_t)i);
+    IREE_ASSERT_OK(iree_vm_list_set_value(list, i, &value));
+  }
+
+  // Truncate to [0, 1) and then extend again.
```
Comment (antiagainst) [inline iree/vm/list_test.cc:258]: [0, 1] or [0, 2)?

Similarly for the others.

**Review by antiagainst — APPROVED** [review]
Ah, refcount magic. :) Still remember the fun I had when trying to debug one previous issue in  parameters pack. Thanks for fixing this!

File: iree/base/CMakeLists.txt (hunk 2 above)
Comment (benvanik) [reply iree/base/CMakeLists.txt:269]: It may still not work on linux (what #2114 was referencing), but the issue was from almost a year ago and we've bumped tracy versions since then. If there are still issues on Linux then someone will need to do a bit of sleuthing to figure out what's wrong as there is likely a legit issue only showing up there that is worth fixing :)
