### PR TITLE
Fixing race on semaphore timepoint cancellation.

### LINKED ISSUE #9392: data race in `iree_hal_task_semaphore_multi_wait`
Repro: enable TSan and run this test:

```
ctest --output-on-failure -R iree/hal/drivers/local_task/cts/local-task_embedded-elf_semaphore_submission_test
```

TSan error:

```
WARNING: ThreadSanitizer: data race (pid=3419395)
  Read of size 8 at 0x7bb000008070 by main thread:
    #0 iree_hal_task_semaphore_multi_wait /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/drivers/local_task/task_semaphore.c:392:60 (local-task_embedded-elf_semaphore_submission_test+0x34a3ad)
    #1 iree_hal_task_device_wait_semaphores /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/drivers/local_task/task_device.c:353:10 (local-task_embedded-elf_semaphore_submission_test+0x3465ae)
    #2 iree_hal_device_wait_semaphores /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/device.c:283:26 (local-task_embedded-elf_semaphore_submission_test+0x344325)
    #3 iree::hal::cts::semaphore_submission_test_SubmitWithMultipleSemaphores_Test::TestBody() /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/cts/semaphore_submission_test.h:194:3 (local-task_embedded-elf_semaphore_submission_test+0x330288)
    #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2607:10 (local-task_embedded-elf_semaphore_submission_test+0x3ccfbf)
    #5 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2643:14 (local-task_embedded-elf_semaphore_submission_test+0x3ccfbf)
    #6 testing::Test::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2682:5 (local-task_embedded-elf_semaphore_submission_test+0x39791f)
    #7 testing::TestInfo::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2861:11 (local-task_embedded-elf_semaphore_submission_test+0x399512)
    #8 testing::TestSuite::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:3015:28 (local-task_embedded-elf_semaphore_submission_test+0x39a3fc)
    #9 testing::internal::UnitTestImpl::RunAllTests() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:5855:44 (local-task_embedded-elf_semaphore_submission_test+0x3b0ec8)
    #10 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2607:10 (local-task_embedded-elf_semaphore_submission_test+0x3ce2ef)
    #11 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2643:14 (local-task_embedded-elf_semaphore_submission_test+0x3ce2ef)
    #12 testing::UnitTest::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:5438:10 (local-task_embedded-elf_semaphore_submission_test+0x3b0010)
    #13 RUN_ALL_TESTS() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/include/gtest/gtest.h:2490:46 (local-task_embedded-elf_semaphore_submission_test+0x3456db)
    #14 main /usr/local/google/home/benoitjacob/iree/runtime/src/iree/testing/gtest_main.cc:17:10 (local-task_embedded-elf_semaphore_submission_test+0x3456db)

  Previous write of size 8 at 0x7bb000008070 by thread T5 (mutexes: write M623):
    #0 memset <null> (local-task_embedded-elf_semaphore_submission_test+0x2c0ebb)
    #1 iree_hal_semaphore_issue_timepoint_callback /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/utils/semaphore_base.c:80:3 (local-task_embedded-elf_semaphore_submission_test+0x34c8e4)
    #2 iree_hal_semaphore_issue_timepoint_callbacks /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/utils/semaphore_base.c:105:5 (local-task_embedded-elf_semaphore_submission_test+0x34c8e4)
    #3 iree_hal_semaphore_resolve_timepoints /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/utils/semaphore_base.c:157:3 (local-task_embedded-elf_semaphore_submission_test+0x34c8e4)
    #4 iree_hal_semaphore_notify /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/utils/semaphore_base.c:286:5 (local-task_embedded-elf_semaphore_submission_test+0x34c8e4)
    #5 iree_hal_task_semaphore_signal /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/drivers/local_task/task_semaphore.c:169:3 (local-task_embedded-elf_semaphore_submission_test+0x34a5d6)
    #6 iree_hal_semaphore_signal /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/semaphore.c:52:7 (local-task_embedded-elf_semaphore_submission_test+0x3453a4)
    #7 iree_hal_task_queue_retire_cmd /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/drivers/local_task/task_queue.c:308:9 (local-task_embedded-elf_semaphore_submission_test+0x349449)
    #8 iree_task_call_execute /usr/local/google/home/benoitjacob/iree/runtime/src/iree/task/task.c:256:28 (local-task_embedded-elf_semaphore_submission_test+0x374926)
    #9 iree_task_worker_execute /usr/local/google/home/benoitjacob/iree/runtime/src/iree/task/worker.c:193:7 (local-task_embedded-elf_semaphore_submission_test+0x376bda)
    #10 iree_task_worker_pump_once /usr/local/google/home/benoitjacob/iree/runtime/src/iree/task/worker.c:256:3 (local-task_embedded-elf_semaphore_submission_test+0x376bda)
    #11 iree_task_worker_pump_until_exit /usr/local/google/home/benoitjacob/iree/runtime/src/iree/task/worker.c:304:12 (local-task_embedded-elf_semaphore_submission_test+0x376bda)
    #12 iree_task_worker_main /usr/local/google/home/benoitjacob/iree/runtime/src/iree/task/worker.c:378:5 (local-task_embedded-elf_semaphore_submission_test+0x376bda)
    #13 iree_thread_start_routine /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/internal/threading_pthreads.c:130:29 (local-task_embedded-elf_semaphore_submission_test+0x38215d)

  Location is heap block of size 32768 at 0x7bb000008000 allocated by main thread:
    #0 malloc <null> (local-task_embedded-elf_semaphore_submission_test+0x2b5f0d)
    #1 iree_allocator_system_alloc /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/allocator.c:88:17 (local-task_embedded-elf_semaphore_submission_test+0x339f67)
    #2 iree_allocator_system_ctl /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/allocator.c:126:14 (local-task_embedded-elf_semaphore_submission_test+0x339f67)
    #3 iree_allocator_issue_alloc /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/allocator.c:27:10 (local-task_embedded-elf_semaphore_submission_test+0x339cf3)
    #4 iree_allocator_malloc_uninitialized /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/allocator.c:38:10 (local-task_embedded-elf_semaphore_submission_test+0x339cf3)
    #5 iree_arena_block_pool_acquire /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/internal/arena.c:75:5 (local-task_embedded-elf_semaphore_submission_test+0x34c1f5)
    #6 iree_arena_allocate /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/internal/arena.c:172:5 (local-task_embedded-elf_semaphore_submission_test+0x34c1f5)
    #7 iree_arena_allocator_ctl /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/internal/arena.c:200:7 (local-task_embedded-elf_semaphore_submission_test+0x34c356)
    #8 iree_allocator_issue_alloc /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/allocator.c:27:10 (local-task_embedded-elf_semaphore_submission_test+0x339c76)
    #9 iree_allocator_malloc /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/allocator.c:32:10 (local-task_embedded-elf_semaphore_submission_test+0x339c76)
    #10 iree_wait_set_allocate /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/internal/wait_handle_poll.c:157:3 (local-task_embedded-elf_semaphore_submission_test+0x377761)
    #11 iree_hal_task_semaphore_multi_wait /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/drivers/local_task/task_semaphore.c:345:26 (local-task_embedded-elf_semaphore_submission_test+0x34a139)
    #12 iree_hal_task_device_wait_semaphores /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/drivers/local_task/task_device.c:353:10 (local-task_embedded-elf_semaphore_submission_test+0x3465ae)
    #13 iree_hal_device_wait_semaphores /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/device.c:283:26 (local-task_embedded-elf_semaphore_submission_test+0x344325)
    #14 iree::hal::cts::semaphore_submission_test_SubmitWithMultipleSemaphores_Test::TestBody() /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/cts/semaphore_submission_test.h:194:3 (local-task_embedded-elf_semaphore_submission_test+0x330288)
    #15 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2607:10 (local-task_embedded-elf_semaphore_submission_test+0x3ccfbf)
    #16 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2643:14 (local-task_embedded-elf_semaphore_submission_test+0x3ccfbf)
    #17 testing::Test::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2682:5 (local-task_embedded-elf_semaphore_submission_test+0x39791f)
    #18 testing::TestInfo::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2861:11 (local-task_embedded-elf_semaphore_submission_test+0x399512)
    #19 testing::TestSuite::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:3015:28 (local-task_embedded-elf_semaphore_submission_test+0x39a3fc)
    #20 testing::internal::UnitTestImpl::RunAllTests() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:5855:44 (local-task_embedded-elf_semaphore_submission_test+0x3b0ec8)
    #21 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2607:10 (local-task_embedded-elf_semaphore_submission_test+0x3ce2ef)
    #22 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2643:14 (local-task_embedded-elf_semaphore_submission_test+0x3ce2ef)
    #23 testing::UnitTest::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:5438:10 (local-task_embedded-elf_semaphore_submission_test+0x3b0010)
    #24 RUN_ALL_TESTS() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/include/gtest/gtest.h:2490:46 (local-task_embedded-elf_semaphore_submission_test+0x3456db)
    #25 main /usr/local/google/home/benoitjacob/iree/runtime/src/iree/testing/gtest_main.cc:17:10 (local-task_embedded-elf_semaphore_submission_test+0x3456db)

  Mutex M623 (0x7b2800000150) created at:
    #0 pthread_mutex_init <null> (local-task_embedded-elf_semaphore_submission_test+0x2b8d0f)
    #1 iree_mutex_initialize /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/internal/synchronization.c:240:3 (local-task_embedded-elf_semaphore_submission_test+0x382526)
    #2 iree_slim_mutex_initialize /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/internal/synchronization.c:494:3 (local-task_embedded-elf_semaphore_submission_test+0x382526)
    #3 iree_hal_semaphore_initialize /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/utils/semaphore_base.c:197:3 (local-task_embedded-elf_semaphore_submission_test+0x34c418)
    #4 iree_hal_task_semaphore_create /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/drivers/local_task/task_semaphore.c:91:5 (local-task_embedded-elf_semaphore_submission_test+0x349ce9)
    #5 iree_hal_task_device_create_semaphore /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/drivers/local_task/task_device.c:302:10 (local-task_embedded-elf_semaphore_submission_test+0x3463bd)
    #6 iree_hal_semaphore_create /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/semaphore.c:29:7 (local-task_embedded-elf_semaphore_submission_test+0x3452ed)
    #7 iree::hal::cts::semaphore_submission_test_SubmitWithMultipleSemaphores_Test::TestBody() /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/cts/semaphore_submission_test.h:155:3 (local-task_embedded-elf_semaphore_submission_test+0x32f6ab)
    #8 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2607:10 (local-task_embedded-elf_semaphore_submission_test+0x3ccfbf)
    #9 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2643:14 (local-task_embedded-elf_semaphore_submission_test+0x3ccfbf)
    #10 testing::Test::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2682:5 (local-task_embedded-elf_semaphore_submission_test+0x39791f)
    #11 testing::TestInfo::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2861:11 (local-task_embedded-elf_semaphore_submission_test+0x399512)
    #12 testing::TestSuite::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:3015:28 (local-task_embedded-elf_semaphore_submission_test+0x39a3fc)
    #13 testing::internal::UnitTestImpl::RunAllTests() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:5855:44 (local-task_embedded-elf_semaphore_submission_test+0x3b0ec8)
    #14 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2607:10 (local-task_embedded-elf_semaphore_submission_test+0x3ce2ef)
    #15 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2643:14 (local-task_embedded-elf_semaphore_submission_test+0x3ce2ef)
    #16 testing::UnitTest::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:5438:10 (local-task_embedded-elf_semaphore_submission_test+0x3b0010)
    #17 RUN_ALL_TESTS() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/include/gtest/gtest.h:2490:46 (local-task_embedded-elf_semaphore_submission_test+0x3456db)
    #18 main /usr/local/google/home/benoitjacob/iree/runtime/src/iree/testing/gtest_main.cc:17:10 (local-task_embedded-elf_semaphore_submission_test+0x3456db)

  Thread T5 'iree-worker-0' (tid=3419425, running) created by main thread at:
    #0 pthread_create <null> (local-task_embedded-elf_semaphore_submission_test+0x2b759d)
    #1 iree_thread_create /usr/local/google/home/benoitjacob/iree/runtime/src/iree/base/internal/threading_pthreads.c:180:10 (local-task_embedded-elf_semaphore_submission_test+0x381c69)
    #2 iree_task_worker_initialize /usr/local/google/home/benoitjacob/iree/runtime/src/iree/task/worker.c:71:26 (local-task_embedded-elf_semaphore_submission_test+0x37683e)
    #3 iree_task_executor_create /usr/local/google/home/benoitjacob/iree/runtime/src/iree/task/executor.c:143:16 (local-task_embedded-elf_semaphore_submission_test+0x370709)
    #4 iree_task_executor_create_from_flags /usr/local/google/home/benoitjacob/iree/runtime/src/iree/task/api.c:104:14 (local-task_embedded-elf_semaphore_submission_test+0x3701c7)
    #5 iree_hal_local_task_driver_factory_try_create /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/drivers/local_task/registration/driver_module.c:55:14 (local-task_embedded-elf_semaphore_submission_test+0x339ab8)
    #6 iree_hal_driver_registry_try_create_by_name /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/driver_registry.c:349:14 (local-task_embedded-elf_semaphore_submission_test+0x3451b8)
    #7 iree::hal::cts::CtsTestBase::TryGetDriver(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, iree_hal_driver_t**) /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/cts/cts_test_base.h:151:28 (local-task_embedded-elf_semaphore_submission_test+0x33597b)
    #8 iree::hal::cts::CtsTestBase::SetUp() /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/cts/cts_test_base.h:48:28 (local-task_embedded-elf_semaphore_submission_test+0x332908)
    #9 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2607:10 (local-task_embedded-elf_semaphore_submission_test+0x3ccfbf)
    #10 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2643:14 (local-task_embedded-elf_semaphore_submission_test+0x3ccfbf)
    #11 testing::Test::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2677:3 (local-task_embedded-elf_semaphore_submission_test+0x39780f)
    #12 testing::TestInfo::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2861:11 (local-task_embedded-elf_semaphore_submission_test+0x399512)
    #13 testing::TestSuite::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:3015:28 (local-task_embedded-elf_semaphore_submission_test+0x39a3fc)
    #14 testing::internal::UnitTestImpl::RunAllTests() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:5855:44 (local-task_embedded-elf_semaphore_submission_test+0x3b0ec8)
    #15 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2607:10 (local-task_embedded-elf_semaphore_submission_test+0x3ce2ef)
    #16 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:2643:14 (local-task_embedded-elf_semaphore_submission_test+0x3ce2ef)
    #17 testing::UnitTest::Run() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/src/gtest.cc:5438:10 (local-task_embedded-elf_semaphore_submission_test+0x3b0010)
    #18 RUN_ALL_TESTS() /usr/local/google/home/benoitjacob/iree/third_party/googletest/googletest/include/gtest/gtest.h:2490:46 (local-task_embedded-elf_semaphore_submission_test+0x3456db)
    #19 main /usr/local/google/home/benoitjacob/iree/runtime/src/iree/testing/gtest_main.cc:17:10 (local-task_embedded-elf_semaphore_submission_test+0x3456db)

SUMMARY: ThreadSanitizer: data race /usr/local/google/home/benoitjacob/iree/runtime/src/iree/hal/drivers/local_task/task_semaphore.c:392:60 in iree_hal_task_semaphore_multi_wait
```

### PR DESCRIPTION
**Pull request by benvanik**
Verified with the repro in the issue.
Fixes #9392.

### CODE REVIEW

File: runtime/src/iree/hal/drivers/local_task/task_semaphore.c [hunk 1]
```diff
@@ -369,6 +370,7 @@ iree_status_t iree_hal_task_semaphore_multi_wait(
         status = iree_hal_task_semaphore_acquire_timepoint(
             semaphore, semaphore_list->payload_values[i], timeout, timepoint);
         if (iree_status_is_ok(status)) {
+          timepoint->semaphore = &semaphore->base;
```
Comment (bjacob) [inline runtime/src/iree/hal/drivers/local_task/task_semaphore.c:373]: I don't feel 100% comfortable with the fact that with this code, iiuc, `timepoint->semaphore`  is NULL initially but then permanently switches to non-NULL once `iree_hal_task_semaphore_multi_wait` has been called. This seems to be unintentially introducing a boolean "mode" here.

Would it be better instead to create a local array of semaphore pointers, local in this `iree_hal_task_semaphore_multi_wait` function? A small heap allocation looks like it would be small overhead compared to what this function already does, this would remove the "mode" issue and would also avoid inflating `iree_hal_task_timepoint_t` ?

Comment (benvanik) [reply runtime/src/iree/hal/drivers/local_task/task_semaphore.c:373]: I think you're asking for what this already does :)
The iree_hal_task_timepoint_t is not cleared - it's only ever set by this code and then checked by it - only the inner iree_hal_timepoint_t is ever modified externally.

Comment (benvanik) [reply runtime/src/iree/hal/drivers/local_task/task_semaphore.c:373]: (the NULL check at the cancel below is just because that's cleanup code and if acquire_timepoint fails midway through a list we only want to cleanup the ones that have been initialized)

Comment (benvanik) [reply runtime/src/iree/hal/drivers/local_task/task_semaphore.c:373]: The timepoints are local to that function - they never escape - so there's nothing but this function that ever knows or cares*. Within the function the timepoint array is created, up to N are initialized, the wait is performed, all initialized timepoints are cancelled, and then the function returns.

* technically they escape into the semaphore timepoint list and may be touched by other threads while in there, but the acquire_timepoint is what inserts them and the cancel_timepoint is what erases them so there's no way for the function to exit without doing that (unless there's a bug) so they're still only extant within the scope of the function.

Comment (benvanik) [reply runtime/src/iree/hal/drivers/local_task/task_semaphore.c:373]: specifically, here's the alloc of the list:
https://github.com/google/iree/blob/9d95e114bad481a0a3703bb81c15267ff1ac3366/runtime/src/iree/hal/drivers/local_task/task_semaphore.c#L357-L358

and the free:
https://github.com/google/iree/blob/9d95e114bad481a0a3703bb81c15267ff1ac3366/runtime/src/iree/hal/drivers/local_task/task_semaphore.c#L401

if a timepoint exists after that area reset there's bigger problems :)

Comment (bjacob) [reply runtime/src/iree/hal/drivers/local_task/task_semaphore.c:373]: Yup, OK. Looks like we are talking the same thing, but you're focusing on what the code is today, while I'm thinking about it in terms of "could this data structure be misused in the future". Anyway, this is a tiny corner of the universe.

**Review by bjacob — APPROVED** [review]
