### PR TITLE
Avoid allocating temporary buffer for tensors derived from read-only tensors

### LINKED ISSUE #5206: failed to legalize operation 'memref.alloc' on GPU in Linalg on Tensors
**Describe the bug**
Some `memref.alloc` will be generated in LinalgBufferizePass. And they do not go away in later passes. I feel that they are some promotion stuff. Because it allocates a buffer and copies the result of `memref.subview` to the allocated buffer.

The full log can be found at https://gist.github.com/hanhanW/d170e9d0372ca4af50eb63be9d0bc6a0

I did not see the issue last week. This is a new failure and was not detected due to lacking tests.
I verified that it starts failing from https://github.com/google/iree/commit/9f968d0cf213d181f37d3a5d6f617e4443ea8d7b
It is passing at https://github.com/google/iree/commit/79b8fbf224275a1bc2b557e57f6ad1ad347d1f6f

Before "Tile and distribute linalg.generic in DispatchLinalgOnTensors" was introduced, the pass won't generate any memref.alloc ops. 

@MaheshRavishankar @ThomasRaoux any clues on this?

note: this only happens on vulkan path. It is doing fine on cpu path.

**To Reproduce**

Run `iree-run-mlir iree/test/e2e/models/edge_detection.mlir -export-all -iree-hal-target-backends=vulkan-spirv -function-input="1x128x128x1xf32" -iree-flow-dispatch-linalg-on-tensors -iree-codegen-spirv-experimental-linalg-on-tensors`

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
If a tensor value for an operand is coming from a read-only tensor,
then the buffer used for the result can be an alias of that used for
the operand since all values derived from a "read-only" tensor is
never written to within the dispatch region.

Fixes #5206

### CODE REVIEW

File: iree/compiler/Conversion/Common/LinalgBufferizePass.cpp [hunk 1]
```diff
@@ -248,6 +248,28 @@ static LogicalResult convertInitTensorOp(
   return success();
 }
 
+/// Walks the use-def chain and see if this value ceoms from a read-only tensor.
```
Comment (antiagainst) [inline iree/compiler/Conversion/Common/LinalgBufferizePass.cpp:251]: s/ceoms/comes/

File: iree/compiler/Conversion/Common/test/linalg_bufferize.mlir [hunk 2]
```diff
@@ -760,3 +760,72 @@ hal.interface @legacy_io attributes {sym_visibility = "private"} {
...
+  %workgroup_size_y = hal.interface.workgroup.size[1] : index
+  %workgroup_id_x = hal.interface.workgroup.id[0] : index
+  %workgroup_count_x = hal.interface.workgroup.count[0] : index
+  %workgroup_id_y = hal.interface.workgroup.id[1] : index
+  %workgroup_count_y = hal.interface.workgroup.count[1] : index
+  %5 = affine.apply affine_map<()[s0, s1] -> (s0 * s1)>()[%workgroup_id_y, %workgroup_size_y]
+  %6 = affine.apply affine_map<()[s0, s1] -> (s0 * s1)>()[%workgroup_count_y, %workgroup_size_y]
+  %dim0 = memref.dim %2, %c0 : tensor<?x?xf32>
+  %dim1 = memref.dim %2, %c1 : tensor<?x?xf32>
+  scf.for %arg0 = %5 to %dim0 step %6 {
```
Comment (antiagainst) [inline iree/compiler/Conversion/Common/test/linalg_bufferize.mlir:784]: For bufferization tests, we don't need the loops? They complicate the test and come at a maintenance cost later when we want to update.

**Review by antiagainst — APPROVED** [review]
Neat!

File: iree/compiler/Conversion/Common/test/linalg_bufferize.mlir (hunk 2 above)
Comment (MaheshRavishankar) [reply iree/compiler/Conversion/Common/test/linalg_bufferize.mlir:784]: Hmmm, I agree. Will leave this as is, and try to not do loops (i obviously borrowed it from a failing test).

**Review by hanhanW — APPROVED** [review]
Nice!

Can we add a simple test that contains `tensor_reshape`?

Maybe something like:

```
func @foo() {
  %0 = hal.interface.binding.subspan @legacy_io::@ro0[%c0] : !flow.dispatch.tensor<readonly:?x?xf32>
  %1 = linalg.tensor_reshape %0 ...
  %2 = linalg.generic { add }
  ...
}
```
